### ISSUE TITLE
Обрати внимание на большие экраны

### ISSUE THREAD

**Issue by yuchiko** [boxior/site-tajam#2]
Сейчас у тебя мешанина c `container` и `container-fluid`
Посмотри как страшно это смотрится, когда текст растягивается на весь экран на экране 5000px, на маленьких он красиво в 5-6 рядов, а тут одна длинная полоса. 

В основном такое комбинирование используется очень редко, потому что контент либо заужен по max-width, либо растягивается на все экраны

**Comment by boxior** [comment]
Изменил все размеры в пикселях на REM, и через медиа запросы менял font-size для HTML тега
